2016-04-23 21:35:30.097 [error] <0.387.0> CRASH REPORT Process <0.387.0> with 0 neighbours exited with reason: call to undefined function local:init('Elixir.RicorEx.Sup', {local,'Elixir.RicorEx.Sup'}) in gen_server:init_it/6 line 352
2016-04-23 21:35:30.099 [error] <0.385.0> CRASH REPORT Process <0.385.0> with 0 neighbours exited with reason: {{undef,[{local,init,['Elixir.RicorEx.Sup',{local,'Elixir.RicorEx.Sup'}],[]},{supervisor,init,1,[{file,"supervisor.erl"},{line,287}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},{'Elixir.RicorEx',start,[normal,[]]}} in application_master:init/4 line 134
2016-04-23 21:35:30.105 [error] <0.6.0> gen_event 'Elixir.Logger.ErrorHandler' installed in error_logger terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"cannot use Logger, the :logger application is not running">>} in 'Elixir.Logger.Config':'__data__'/0 line 53
